version: '2'
services:
    slack_bot:
        build:
            context: ./
            dockerfile: app.docker
        links:
            - slack_bot_mongo
        volumes:
            - ../:/code
    slack_bot_mongo:
        image: mongo:latest
        ports:
            - "27017:27017"